[[menu.shortcuts]]
name = "<img src=/images/forticloud.svg class=sidebaricon></img> FortiCloud Login"
url = "https://login.forticloud.com"
weight = 1

[[menu.shortcuts]]
name = "<img src=/images/forticnp.svg class=sidebaricon></img> FortiCNP Login"
url = "https://login.forticloud.com"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-book-open'></i> Documentation"
url = "https://docs.fortinet.com/document/forticnp/22.4.a/online-help/"
weight = 3

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Knowledge Base"
url = "https://community.fortinet.com/t5/FortiCNP/tkb-p/TKB38"
weight = 4

[params]
  editURL = "https://github.com/robinmordasiewicz/fortinet-forticnp-hugo-md/edit/main/"
  logoBannerText="FortiCNP"
  logoBannerSubText="Version 22.4a"
  googleAnalytics = 'G-D0GB95LVDG'
