[[menu.shortcuts]]
name = "<img src=/images/forticloud.svg class=sidebaricon></img> FortiCloud Login"
url = "https://login.forticloud.com"
weight = 1

[[menu.shortcuts]]
name = "<img src=/images/forticnp.svg class=sidebaricon></img> FortiCNP Login"
url = "https://login.forticloud.com"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-book-open'></i> Documentation"
url = "https://docs.fortinet.com/document/forticnp/22.4.a/online-help/"
weight = 3

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Knowledge Base"
url = "https://community.fortinet.com/t5/FortiCNP/tkb-p/TKB38"
weight = 4

[params]
  editURL = "https://github.com/robinmordasiewicz/fortinet-forticnp-hugo-md/edit/main/"
  logoBannerText="FortiCNP"
  logoBannerSubText="Version 22.4a"

[comments]
  provider = "giscus"
  commentable = {page = true, post = true, docs = false, project = false, publication = true, talk = false}

  [comments.giscus]
    repo = "robinmordasiewicz/fortinet-forticnp-hugo-md"
    repo_id = "R_kgDOJtuM1w"
    category = "General"
    category_id = "DIC_kwDOJtuM184CXPYd"
    mapping = "pathname"
    label = "comment"
    theme = "light"
    reactions_enabled = 0
    strict = 0
    emit-metadata = 0
    input-position = "bottom"
    lang = "en"
    crossorigin = "anonymous"
