name: create-gif

on:
  pull_request:
    paths:
      - '**.mov'
    branches:
      - main
  push:
    paths:
      - '**.mov'
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        uses: hmarr/debug-action@v2
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2

