name: create-gif

on:
  pull_request:
    paths:
      - '**.mov'
    branches:
      - main
  push:
    paths:
      - '**.mov'
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Debug
        uses: hmarr/debug-action@v2
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      - name: Install gifski
        run: curl -sLO https://github.com/ImageOptim/gifski/releases/download/1.11.0/gifski_1.11.0_amd64.deb && sudo apt-get update && sudo apt install ./gifski_1.11.0_amd64.deb
      - name: Checkout Content
        uses: actions/checkout@v3
      - name: Reduce frame rate
        run: ffmpeg -nostats -loglevel 0 -y -i forticloud-forticnp-login.mov -filter:v fps=fps=15 forticloud-forticnp-login-fps.mov
      - name: Create a border
        run: ffmpeg -nostats -loglevel 0 -y -i forticloud-forticnp-login-fps.mov -pix_fmt yuv420p -filter_complex "[0]pad=w=4+iw:h=4+ih:x=2:y=2:color=black" forticloud-forticnp-login-fps-border.mov
      - name: Convert to gif
        run: gifski -q -Q 100 --lossy-quality 100 --fps 10 --width 1920 --repeat -1 -o forticloud-forticnp-login.gif forticloud-forticnp-login-fps-border.mov
      - name: git status
        run: git status
