name: webhook

on:
  workflow_call:
  pull_request:
    paths-ignore:
      - "README.md"
    branches:
      - main
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

concurrency:
  group: "content"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GHA_WORKFLOW_TRIGGER }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            'robinmordasiewicz',
            'fortinet-hugo-theme',
            'workflows/content.yaml',
            'main'
          });

